apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default "business-service" }}
  namespace: {{ .Values.namespace | default "business-service" }}
  labels:
    {{- include "business-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "business-service.labels" . | nindent 6 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}