apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.destinationRule.name }}
  namespace: {{ .Values.defaults.namespace }}
spec:
  host: {{ .Values.defaults.host }}
  subsets:
  - name: stable
    labels:
      version: {{ .Values.subsets.stable.version }}
  - name: canary
    labels:
      version: {{ .Values.subsets.canary.version }}
